package com.drip.admin.modules.system.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.drip.admin.common.exception.BusinessException;
import com.drip.admin.common.response.BackupFile;
import com.drip.admin.common.response.PageResult;
import com.drip.admin.modules.system.dto.DatabaseBackupCreateRequest;
import com.drip.admin.modules.system.dto.DatabaseBackupQuery;
import com.drip.admin.modules.system.dto.DatabaseRestoreRequest;
import com.drip.admin.modules.system.entity.SysDbBackupEntity;
import com.drip.admin.modules.system.mapper.SysDbBackupMapper;
import com.drip.admin.modules.system.service.DatabaseBackupService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

@Service
public class DatabaseBackupServiceImpl extends ServiceImpl<SysDbBackupMapper, SysDbBackupEntity> implements DatabaseBackupService {
    private final Path backupDir; private final String datasourceUrl; private final String datasourceUsername; private final String datasourcePassword; private final String mysqldumpCommand; private final String mysqlCommand;
    public DatabaseBackupServiceImpl(@Value("${drip.database.backup-dir}") String backupDir, @Value("${spring.datasource.url}") String datasourceUrl, @Value("${spring.datasource.username}") String datasourceUsername, @Value("${spring.datasource.password}") String datasourcePassword, @Value("${drip.database.mysqldump-command:mysqldump}") String mysqldumpCommand, @Value("${drip.database.mysql-command:mysql}") String mysqlCommand) { this.backupDir = Path.of(backupDir); this.datasourceUrl = datasourceUrl; this.datasourceUsername = datasourceUsername; this.datasourcePassword = datasourcePassword; this.mysqldumpCommand = mysqldumpCommand; this.mysqlCommand = mysqlCommand; }
    @Override public PageResult<SysDbBackupEntity> page(DatabaseBackupQuery query) { int page = query.pageOrDefault(); int pageSize = query.pageSizeOrDefault(); Page<SysDbBackupEntity> result = page(new Page<>(page, pageSize), new QueryWrapper<SysDbBackupEntity>().orderByDesc("created_at")); return new PageResult<>(result.getRecords(), result.getTotal(), page, pageSize); }
    @Override public Long create(DatabaseBackupCreateRequest request, long userId) { try { Files.createDirectories(backupDir); String name = "backup-" + System.currentTimeMillis() + ".sql"; Path normalizedDir = backupDir.toAbsolutePath().normalize(); Path target = normalizedDir.resolve(name).normalize(); if (!target.startsWith(normalizedDir)) throw new BusinessException(400000, "operation failed"); MysqlTarget mysqlTarget = parseMysqlTarget(); runProcess(List.of(mysqldumpCommand, "-h", mysqlTarget.host(), "-P", String.valueOf(mysqlTarget.port()), "-u" + datasourceUsername, "--single-transaction", "--routines", "--default-character-set=utf8mb4", mysqlTarget.database()), target, null); SysDbBackupEntity entity = new SysDbBackupEntity(); entity.setBackupName(name); entity.setFilePath(target.toString()); entity.setFileSize(Files.size(target)); entity.setStatus("SUCCESS"); entity.setCreatedBy(userId); entity.setRemark(request == null ? null : request.getRemark()); save(entity); return entity.getId(); } catch (IOException ex) { throw new BusinessException(500000, "operation failed"); } }
    @Override public BackupFile download(long id) throws IOException { SysDbBackupEntity backup = detail(id); Path path = Path.of(backup.getFilePath()).normalize(); if (!Files.exists(path)) throw new BusinessException(404000, "operation failed"); return new BackupFile(backup.getBackupName(), Files.readAllBytes(path)); }
    @Override public void restore(long id, DatabaseRestoreRequest request) { SysDbBackupEntity backup = detail(id); if (request == null || !Boolean.TRUE.equals(request.getConfirmed())) throw new BusinessException(400000, "operation failed"); Path path = Path.of(backup.getFilePath()).toAbsolutePath().normalize(); if (!Files.exists(path)) throw new BusinessException(404000, "operation failed"); MysqlTarget mysqlTarget = parseMysqlTarget(); runProcess(List.of(mysqlCommand, "-h", mysqlTarget.host(), "-P", String.valueOf(mysqlTarget.port()), "-u" + datasourceUsername, "--default-character-set=utf8mb4", mysqlTarget.database()), null, path); }
    @Override public void delete(long id) { SysDbBackupEntity backup = detail(id); Path path = Path.of(backup.getFilePath()).toAbsolutePath().normalize(); try { Files.deleteIfExists(path); } catch (IOException ex) { throw new BusinessException(500000, "operation failed"); } removeById(id); }
    private SysDbBackupEntity detail(long id) { SysDbBackupEntity entity = getById(id); if (entity == null) throw new BusinessException(404000, "operation failed"); return entity; }
    private MysqlTarget parseMysqlTarget() { try { String raw = datasourceUrl.substring("jdbc:".length()); URI uri = URI.create(raw); String database = uri.getPath() == null ? "" : uri.getPath().replaceFirst("^/", ""); if (database.isBlank()) throw new BusinessException(500000, "MySQL database name is missing"); return new MysqlTarget(uri.getHost(), uri.getPort() > 0 ? uri.getPort() : 3306, database); } catch (IllegalArgumentException | IndexOutOfBoundsException ex) { throw new BusinessException(500000, "Invalid MySQL datasource url"); } }
    private void runProcess(List<String> command, Path stdoutFile, Path stdinFile) { ProcessBuilder builder = new ProcessBuilder(command); builder.environment().put("MYSQL_PWD", datasourcePassword); Path tempStdout = null; Path tempStderr = null; Path actualStdout = stdoutFile; Path actualStderr; if (actualStdout == null) { try { tempStdout = Files.createTempFile("drip-db-command-", ".out"); actualStdout = tempStdout; } catch (IOException ex) { throw new BusinessException(500000, "database command temp output is not available"); } } try { tempStderr = Files.createTempFile("drip-db-command-", ".err"); actualStderr = tempStderr; } catch (IOException ex) { throw new BusinessException(500000, "database command temp error output is not available"); } if (stdoutFile != null) builder.redirectOutput(stdoutFile.toFile()); else builder.redirectOutput(actualStdout.toFile()); if (stdinFile != null) builder.redirectInput(stdinFile.toFile()); builder.redirectError(actualStderr.toFile()); builder.redirectErrorStream(false); try { if (stdoutFile != null) Files.deleteIfExists(stdoutFile); Process process = builder.start(); int exit = process.waitFor(); String stdout = actualStdout == null || !Files.exists(actualStdout) ? "" : Files.readString(actualStdout, StandardCharsets.UTF_8); String stderr = actualStderr == null || !Files.exists(actualStderr) ? "" : Files.readString(actualStderr, StandardCharsets.UTF_8); if (exit != 0) { if (stdoutFile != null) Files.deleteIfExists(stdoutFile); throw new BusinessException(500000, "database command failed: " + (stderr.isBlank() ? stdout : stderr)); } } catch (IOException ex) { throw new BusinessException(500000, "database command is not available: " + command.getFirst()); } catch (InterruptedException ex) { Thread.currentThread().interrupt(); throw new BusinessException(500000, "database command interrupted"); } finally { try { if (tempStdout != null) Files.deleteIfExists(tempStdout); if (tempStderr != null) Files.deleteIfExists(tempStderr); } catch (IOException ignored) { } } }
    private record MysqlTarget(String host, int port, String database) { }
}
