import type { Component } from 'vue';

export const antIconNames = [
  'AccountBookFilled',
  'AccountBookTwoTone',
  'AlertFilled',
  'AlertOutlined',
  'AlertTwoTone',
  'AlibabaOutlined',
  'AlignCenterOutlined',
  'AlignLeftOutlined',
  'AlignRightOutlined',
  'AlipayCircleFilled',
  'AlipayCircleOutlined',
  'AlipayOutlined',
  'AlipaySquareFilled',
  'AliwangwangFilled',
  'AliwangwangOutlined',
  'AliyunOutlined',
  'AmazonCircleFilled',
  'AmazonOutlined',
  'AmazonSquareFilled',
  'AndroidFilled',
  'AndroidOutlined',
  'AntCloudOutlined',
  'AntDesignOutlined',
  'ApiFilled',
  'ApiOutlined',
  'ApiTwoTone',
  'AppleFilled',
  'AppleOutlined',
  'AppstoreAddOutlined',
  'AppstoreFilled',
  'AppstoreTwoTone',
  'ArrowDownOutlined',
  'ArrowUpOutlined',
  'ArrowsAltOutlined',
  'AudioFilled',
  'AudioMutedOutlined',
  'AudioOutlined',
  'AudioTwoTone',
  'BackwardFilled',
  'BackwardOutlined',
  'BankFilled',
  'BankTwoTone',
  'BehanceCircleFilled',
  'BehanceOutlined',
  'BehanceSquareFilled',
  'BehanceSquareOutlined',
  'BellFilled',
  'BellTwoTone',
  'BgColorsOutlined',
  'BlockOutlined',
  'BoldOutlined',
  'BookFilled',
  'BookTwoTone',
  'BorderBottomOutlined',
  'BorderHorizontalOutlined',
  'BorderInnerOutlined',
  'BorderLeftOutlined',
  'BorderOuterOutlined',
  'BorderOutlined',
  'BorderRightOutlined',
  'BorderTopOutlined',
  'BorderVerticleOutlined',
  'BorderlessTableOutlined',
  'BoxPlotFilled',
  'BoxPlotOutlined',
  'BoxPlotTwoTone',
  'BugFilled',
  'BugOutlined',
  'BugTwoTone',
  'BuildFilled',
  'BuildTwoTone',
  'BulbFilled',
  'BulbOutlined',
  'BulbTwoTone',
  'CalculatorFilled',
  'CalculatorTwoTone',
  'CalendarFilled',
  'CalendarTwoTone',
  'CameraFilled',
  'CameraOutlined',
  'CameraTwoTone',
  'CarFilled',
  'CarTwoTone',
  'CaretLeftFilled',
  'CaretLeftOutlined',
  'CaretRightFilled',
  'CaretRightOutlined',
  'CaretUpFilled',
  'CarryOutFilled',
  'CarryOutOutlined',
  'CarryOutTwoTone',
  'CheckCircleTwoTone',
  'CheckSquareFilled',
  'CheckSquareOutlined',
  'CheckSquareTwoTone',
  'ChromeFilled',
  'ChromeOutlined',
  'CiCircleFilled',
  'CiCircleOutlined',
  'CiCircleTwoTone',
  'CiOutlined',
  'CiTwoTone',
  'ClearOutlined',
  'ClockCircleFilled',
  'ClockCircleTwoTone',
  'CloseCircleTwoTone',
  'CloseSquareFilled',
  'CloseSquareOutlined',
  'CloseSquareTwoTone',
  'CloudDownloadOutlined',
  'CloudFilled',
  'CloudOutlined',
  'CloudSyncOutlined',
  'CloudTwoTone',
  'CloudUploadOutlined',
  'CodeFilled',
  'CodeOutlined',
  'CodeSandboxCircleFilled',
  'CodeSandboxSquareFilled',
  'CodeTwoTone',
  'CodepenCircleFilled',
  'CodepenCircleOutlined',
  'CodepenOutlined',
  'CodepenSquareFilled',
  'CoffeeOutlined',
  'CommentOutlined',
  'CompassFilled',
  'CompassOutlined',
  'CompassTwoTone',
  'CompressOutlined',
  'ConsoleSqlOutlined',
  'ContactsFilled',
  'ContactsOutlined',
  'ContactsTwoTone',
  'ContainerFilled',
  'ContainerTwoTone',
  'ControlFilled',
  'ControlTwoTone',
  'CopyFilled',
  'CopyTwoTone',
  'CopyrightCircleFilled',
  'CopyrightCircleOutlined',
  'CopyrightCircleTwoTone',
  'CopyrightOutlined',
  'CopyrightTwoTone',
  'CreditCardFilled',
  'CreditCardTwoTone',
  'CrownFilled',
  'CrownOutlined',
  'CrownTwoTone',
  'CustomerServiceFilled',
  'CustomerServiceOutlined',
  'CustomerServiceTwoTone',
  'DashOutlined',
  'DashboardFilled',
  'DashboardTwoTone',
  'DatabaseFilled',
  'DatabaseTwoTone',
  'DeleteColumnOutlined',
  'DeleteFilled',
  'DeleteRowOutlined',
  'DeleteTwoTone',
  'DeliveredProcedureOutlined',
  'DesktopOutlined',
  'DiffFilled',
  'DiffOutlined',
  'DiffTwoTone',
  'DingdingOutlined',
  'DingtalkCircleFilled',
  'DingtalkOutlined',
  'DingtalkSquareFilled',
  'DisconnectOutlined',
  'DislikeFilled',
  'DislikeOutlined',
  'DislikeTwoTone',
  'DollarCircleFilled',
  'DollarCircleOutlined',
  'DollarCircleTwoTone',
  'DollarTwoTone',
  'DotChartOutlined',
  'DownCircleFilled',
  'DownCircleOutlined',
  'DownCircleTwoTone',
  'DownSquareFilled',
  'DownSquareOutlined',
  'DownSquareTwoTone',
  'DragOutlined',
  'DribbbleCircleFilled',
  'DribbbleOutlined',
  'DribbbleSquareFilled',
  'DribbbleSquareOutlined',
  'DropboxCircleFilled',
  'DropboxSquareFilled',
  'EditFilled',
  'EditTwoTone',
  'EnvironmentFilled',
  'EnvironmentTwoTone',
  'EuroCircleFilled',
  'EuroCircleOutlined',
  'EuroCircleTwoTone',
  'EuroOutlined',
  'EuroTwoTone',
  'ExceptionOutlined',
  'ExclamationCircleTwoTone',
  'ExclamationOutlined',
  'ExpandAltOutlined',
  'ExpandOutlined',
  'ExperimentFilled',
  'ExperimentOutlined',
  'ExperimentTwoTone',
  'EyeFilled',
  'EyeInvisibleFilled',
  'EyeInvisibleTwoTone',
  'EyeTwoTone',
  'FacebookFilled',
  'FacebookOutlined',
  'FastBackwardFilled',
  'FastBackwardOutlined',
  'FastForwardFilled',
  'FastForwardOutlined',
  'FieldBinaryOutlined',
  'FieldStringOutlined',
  'FieldTimeOutlined',
  'FileAddFilled',
  'FileAddOutlined',
  'FileAddTwoTone',
  'FileExcelFilled',
  'FileExcelOutlined',
  'FileExcelTwoTone',
  'FileExclamationFilled',
  'FileExclamationOutlined',
  'FileExclamationTwoTone',
  'FileFilled',
  'FileGifOutlined',
  'FileImageFilled',
  'FileImageOutlined',
  'FileImageTwoTone',
  'FileJpgOutlined',
  'FileMarkdownFilled',
  'FileMarkdownOutlined',
  'FileMarkdownTwoTone',
  'FilePdfFilled',
  'FilePdfOutlined',
  'FilePdfTwoTone',
  'FilePptFilled',
  'FilePptOutlined',
  'FilePptTwoTone',
  'FileTextFilled',
  'FileTextTwoTone',
  'FileUnknownFilled',
  'FileUnknownOutlined',
  'FileUnknownTwoTone',
  'FileWordFilled',
  'FileWordOutlined',
  'FileWordTwoTone',
  'FileZipFilled',
  'FileZipOutlined',
  'FileZipTwoTone',
  'FilterOutlined',
  'FilterTwoTone',
  'FireFilled',
  'FireOutlined',
  'FireTwoTone',
  'FlagFilled',
  'FlagOutlined',
  'FlagTwoTone',
  'FolderAddFilled',
  'FolderAddOutlined',
  'FolderAddTwoTone',
  'FolderFilled',
  'FolderOpenFilled',
  'FolderOpenTwoTone',
  'FolderTwoTone',
  'FolderViewOutlined',
  'FontColorsOutlined',
  'FontSizeOutlined',
  'FormOutlined',
  'FormatPainterFilled',
  'FormatPainterOutlined',
  'ForwardFilled',
  'ForwardOutlined',
  'FrownFilled',
  'FrownOutlined',
  'FrownTwoTone',
  'FullscreenExitOutlined',
  'FullscreenOutlined',
  'FunctionOutlined',
  'FundFilled',
  'FundProjectionScreenOutlined',
  'FundTwoTone',
  'FundViewOutlined',
  'FunnelPlotFilled',
  'FunnelPlotOutlined',
  'FunnelPlotTwoTone',
  'GifOutlined',
  'GiftFilled',
  'GiftOutlined',
  'GiftTwoTone',
  'GithubFilled',
  'GithubOutlined',
  'GitlabFilled',
  'GitlabOutlined',
  'GoldFilled',
  'GoldTwoTone',
  'GoldenFilled',
  'GoogleCircleFilled',
  'GoogleOutlined',
  'GooglePlusCircleFilled',
  'GooglePlusOutlined',
  'GooglePlusSquareFilled',
  'GoogleSquareFilled',
  'GroupOutlined',
  'HddFilled',
  'HddTwoTone',
  'HeartFilled',
  'HeartOutlined',
  'HeartTwoTone',
  'HeatMapOutlined',
  'HighlightFilled',
  'HighlightOutlined',
  'HighlightTwoTone',
  'HolderOutlined',
  'HomeFilled',
  'HomeTwoTone',
  'HourglassFilled',
  'HourglassOutlined',
  'HourglassTwoTone',
  'Html5Filled',
  'Html5Outlined',
  'Html5TwoTone',
  'IdcardFilled',
  'IdcardOutlined',
  'IdcardTwoTone',
  'IeCircleFilled',
  'IeOutlined',
  'IeSquareFilled',
  'InfoCircleTwoTone',
  'InfoOutlined',
  'InsertRowAboveOutlined',
  'InsertRowBelowOutlined',
  'InsertRowLeftOutlined',
  'InsertRowRightOutlined',
  'InstagramFilled',
  'InstagramOutlined',
  'InsuranceFilled',
  'InsuranceOutlined',
  'InsuranceTwoTone',
  'InteractionFilled',
  'InteractionOutlined',
  'InteractionTwoTone',
  'IssuesCloseOutlined',
  'ItalicOutlined',
  'LaptopOutlined',
  'LayoutFilled',
  'LayoutTwoTone',
  'LeftCircleFilled',
  'LeftCircleOutlined',
  'LeftCircleTwoTone',
  'LeftSquareFilled',
  'LeftSquareOutlined',
  'LeftSquareTwoTone',
  'LikeFilled',
  'LikeOutlined',
  'LikeTwoTone',
  'LineHeightOutlined',
  'LineOutlined',
  'LinkOutlined',
  'LinkedinFilled',
  'LinkedinOutlined',
  'Loading3QuartersOutlined',
  'LockFilled',
  'LockTwoTone',
  'LoginOutlined',
  'LogoutOutlined',
  'MacCommandFilled',
  'MacCommandOutlined',
  'MailFilled',
  'MailOutlined',
  'MailTwoTone',
  'ManOutlined',
  'MedicineBoxFilled',
  'MedicineBoxOutlined',
  'MedicineBoxTwoTone',
  'MediumCircleFilled',
  'MediumOutlined',
  'MediumSquareFilled',
  'MediumWorkmarkOutlined',
  'MehFilled',
  'MehOutlined',
  'MehTwoTone',
  'MergeCellsOutlined',
  'MessageFilled',
  'MessageOutlined',
  'MessageTwoTone',
  'MinusCircleFilled',
  'MinusCircleOutlined',
  'MinusCircleTwoTone',
  'MinusOutlined',
  'MinusSquareFilled',
  'MinusSquareTwoTone',
  'MobileFilled',
  'MobileOutlined',
  'MobileTwoTone',
  'MoneyCollectFilled',
  'MoneyCollectOutlined',
  'MoneyCollectTwoTone',
  'MonitorOutlined',
  'MoreOutlined',
  'NodeCollapseOutlined',
  'NodeExpandOutlined',
  'NotificationFilled',
  'NotificationOutlined',
  'NotificationTwoTone',
  'OneToOneOutlined',
  'OrderedListOutlined',
  'PauseCircleFilled',
  'PauseCircleOutlined',
  'PauseCircleTwoTone',
  'PauseOutlined',
  'PayCircleFilled',
  'PercentageOutlined',
  'PhoneFilled',
  'PhoneOutlined',
  'PhoneTwoTone',
  'PicCenterOutlined',
  'PicLeftOutlined',
  'PicRightOutlined',
  'PictureFilled',
  'PictureOutlined',
  'PieChartFilled',
  'PieChartTwoTone',
  'PlayCircleFilled',
  'PlayCircleOutlined',
  'PlayCircleTwoTone',
  'PlaySquareFilled',
  'PlaySquareOutlined',
  'PlaySquareTwoTone',
  'PlusCircleFilled',
  'PlusCircleOutlined',
  'PlusCircleTwoTone',
  'PlusSquareFilled',
  'PlusSquareTwoTone',
  'PoundCircleFilled',
  'PoundCircleOutlined',
  'PoundCircleTwoTone',
  'PoundOutlined',
  'PoweroffOutlined',
  'PrinterFilled',
  'PrinterOutlined',
  'PrinterTwoTone',
  'ProfileFilled',
  'ProfileTwoTone',
  'ProjectFilled',
  'ProjectOutlined',
  'ProjectTwoTone',
  'PropertySafetyFilled',
  'PropertySafetyOutlined',
  'PropertySafetyTwoTone',
  'PullRequestOutlined',
  'PushpinFilled',
  'PushpinOutlined',
  'PushpinTwoTone',
  'QqCircleFilled',
  'QqOutlined',
  'QqSquareFilled',
  'QuestionCircleFilled',
  'QuestionCircleTwoTone',
  'QuestionOutlined',
  'RadarChartOutlined',
  'RadiusBottomleftOutlined',
  'RadiusBottomrightOutlined',
  'RadiusSettingOutlined',
  'RadiusUpleftOutlined',
  'RadiusUprightOutlined',
  'ReadFilled',
  'ReadOutlined',
  'ReconciliationFilled',
  'ReconciliationTwoTone',
  'RedEnvelopeFilled',
  'RedEnvelopeOutlined',
  'RedEnvelopeTwoTone',
  'RedditCircleFilled',
  'RedditOutlined',
  'RedditSquareFilled',
  'RedoOutlined',
  'RestFilled',
  'RestTwoTone',
  'RightCircleFilled',
  'RightCircleOutlined',
  'RightCircleTwoTone',
  'RightSquareFilled',
  'RightSquareOutlined',
  'RightSquareTwoTone',
  'RobotFilled',
  'RobotOutlined',
  'RocketFilled',
  'RocketOutlined',
  'RocketTwoTone',
  'RollbackOutlined',
  'SafetyCertificateFilled',
  'SafetyCertificateTwoTone',
  'SafetyOutlined',
  'SaveFilled',
  'SaveOutlined',
  'SaveTwoTone',
  'ScanOutlined',
  'ScheduleFilled',
  'ScheduleTwoTone',
  'ScissorOutlined',
  'SecurityScanFilled',
  'SecurityScanOutlined',
  'SecurityScanTwoTone',
  'SelectOutlined',
  'SettingFilled',
  'SettingTwoTone',
  'ShakeOutlined',
  'ShareAltOutlined',
  'ShopFilled',
  'ShopTwoTone',
  'ShoppingFilled',
  'ShoppingTwoTone',
  'ShrinkOutlined',
  'SignalFilled',
  'SisternodeOutlined',
  'SketchCircleFilled',
  'SketchOutlined',
  'SketchSquareFilled',
  'SkinFilled',
  'SkinOutlined',
  'SkinTwoTone',
  'SkypeFilled',
  'SkypeOutlined',
  'SlackCircleFilled',
  'SlackOutlined',
  'SlackSquareFilled',
  'SlackSquareOutlined',
  'SlidersFilled',
  'SlidersTwoTone',
  'SmallDashOutlined',
  'SmileFilled',
  'SmileOutlined',
  'SmileTwoTone',
  'SnippetsFilled',
  'SnippetsOutlined',
  'SnippetsTwoTone',
  'SortAscendingOutlined',
  'SortDescendingOutlined',
  'SoundFilled',
  'SoundOutlined',
  'SoundTwoTone',
  'SplitCellsOutlined',
  'StarOutlined',
  'StarTwoTone',
  'StepBackwardFilled',
  'StepBackwardOutlined',
  'StepForwardFilled',
  'StepForwardOutlined',
  'StopFilled',
  'StopOutlined',
  'StopTwoTone',
  'StrikethroughOutlined',
  'SubnodeOutlined',
  'SwapLeftOutlined',
  'SwitcherFilled',
  'SwitcherOutlined',
  'SwitcherTwoTone',
  'SyncOutlined',
  'TabletFilled',
  'TabletOutlined',
  'TabletTwoTone',
  'TagFilled',
  'TagOutlined',
  'TagTwoTone',
  'TagsFilled',
  'TagsTwoTone',
  'TaobaoCircleFilled',
  'TaobaoCircleOutlined',
  'TaobaoOutlined',
  'TaobaoSquareFilled',
  'ThunderboltFilled',
  'ThunderboltOutlined',
  'ThunderboltTwoTone',
  'ToTopOutlined',
  'ToolFilled',
  'ToolTwoTone',
  'TrademarkCircleFilled',
  'TrademarkCircleOutlined',
  'TrademarkCircleTwoTone',
  'TrademarkOutlined',
  'TransactionOutlined',
  'TranslationOutlined',
  'TrophyFilled',
  'TrophyOutlined',
  'TrophyTwoTone',
  'TwitterCircleFilled',
  'TwitterOutlined',
  'TwitterSquareFilled',
  'UnderlineOutlined',
  'UndoOutlined',
  'UngroupOutlined',
  'UnlockFilled',
  'UnlockOutlined',
  'UnlockTwoTone',
  'UnorderedListOutlined',
  'UpCircleFilled',
  'UpCircleOutlined',
  'UpCircleTwoTone',
  'UpSquareFilled',
  'UpSquareOutlined',
  'UpSquareTwoTone',
  'UploadOutlined',
  'UsbFilled',
  'UsbOutlined',
  'UsbTwoTone',
  'UserAddOutlined',
  'UserDeleteOutlined',
  'UserSwitchOutlined',
  'UsergroupAddOutlined',
  'UsergroupDeleteOutlined',
  'VerifiedOutlined',
  'VerticalAlignBottomOutlined',
  'VerticalAlignMiddleOutlined',
  'VerticalLeftOutlined',
  'VerticalRightOutlined',
  'VideoCameraAddOutlined',
  'VideoCameraFilled',
  'VideoCameraOutlined',
  'VideoCameraTwoTone',
  'WalletFilled',
  'WalletTwoTone',
  'WarningTwoTone',
  'WechatFilled',
  'WechatOutlined',
  'WeiboCircleFilled',
  'WeiboCircleOutlined',
  'WeiboOutlined',
  'WeiboSquareFilled',
  'WeiboSquareOutlined',
  'WhatsAppOutlined',
  'WifiOutlined',
  'WindowsFilled',
  'WindowsOutlined',
  'WomanOutlined',
  'YahooFilled',
  'YahooOutlined',
  'YoutubeFilled',
  'YoutubeOutlined',
  'YuqueFilled',
  'YuqueOutlined',
  'ZhihuCircleFilled',
  'ZhihuOutlined',
  'ZhihuSquareFilled',
] as const;

export type AntIconName = (typeof antIconNames)[number];
export type AntIconLoader = () => Promise<{ default: Component }>;

export const antIconNameSet = new Set<string>(antIconNames);

export const antIconLoaders: Record<AntIconName, AntIconLoader> = {
  AccountBookFilled: () => import('@ant-design/icons-vue/es/icons/AccountBookFilled.js'),
  AccountBookTwoTone: () => import('@ant-design/icons-vue/es/icons/AccountBookTwoTone.js'),
  AlertFilled: () => import('@ant-design/icons-vue/es/icons/AlertFilled.js'),
  AlertOutlined: () => import('@ant-design/icons-vue/es/icons/AlertOutlined.js'),
  AlertTwoTone: () => import('@ant-design/icons-vue/es/icons/AlertTwoTone.js'),
  AlibabaOutlined: () => import('@ant-design/icons-vue/es/icons/AlibabaOutlined.js'),
  AlignCenterOutlined: () => import('@ant-design/icons-vue/es/icons/AlignCenterOutlined.js'),
  AlignLeftOutlined: () => import('@ant-design/icons-vue/es/icons/AlignLeftOutlined.js'),
  AlignRightOutlined: () => import('@ant-design/icons-vue/es/icons/AlignRightOutlined.js'),
  AlipayCircleFilled: () => import('@ant-design/icons-vue/es/icons/AlipayCircleFilled.js'),
  AlipayCircleOutlined: () => import('@ant-design/icons-vue/es/icons/AlipayCircleOutlined.js'),
  AlipayOutlined: () => import('@ant-design/icons-vue/es/icons/AlipayOutlined.js'),
  AlipaySquareFilled: () => import('@ant-design/icons-vue/es/icons/AlipaySquareFilled.js'),
  AliwangwangFilled: () => import('@ant-design/icons-vue/es/icons/AliwangwangFilled.js'),
  AliwangwangOutlined: () => import('@ant-design/icons-vue/es/icons/AliwangwangOutlined.js'),
  AliyunOutlined: () => import('@ant-design/icons-vue/es/icons/AliyunOutlined.js'),
  AmazonCircleFilled: () => import('@ant-design/icons-vue/es/icons/AmazonCircleFilled.js'),
  AmazonOutlined: () => import('@ant-design/icons-vue/es/icons/AmazonOutlined.js'),
  AmazonSquareFilled: () => import('@ant-design/icons-vue/es/icons/AmazonSquareFilled.js'),
  AndroidFilled: () => import('@ant-design/icons-vue/es/icons/AndroidFilled.js'),
  AndroidOutlined: () => import('@ant-design/icons-vue/es/icons/AndroidOutlined.js'),
  AntCloudOutlined: () => import('@ant-design/icons-vue/es/icons/AntCloudOutlined.js'),
  AntDesignOutlined: () => import('@ant-design/icons-vue/es/icons/AntDesignOutlined.js'),
  ApiFilled: () => import('@ant-design/icons-vue/es/icons/ApiFilled.js'),
  ApiOutlined: () => import('@ant-design/icons-vue/es/icons/ApiOutlined.js'),
  ApiTwoTone: () => import('@ant-design/icons-vue/es/icons/ApiTwoTone.js'),
  AppleFilled: () => import('@ant-design/icons-vue/es/icons/AppleFilled.js'),
  AppleOutlined: () => import('@ant-design/icons-vue/es/icons/AppleOutlined.js'),
  AppstoreAddOutlined: () => import('@ant-design/icons-vue/es/icons/AppstoreAddOutlined.js'),
  AppstoreFilled: () => import('@ant-design/icons-vue/es/icons/AppstoreFilled.js'),
  AppstoreTwoTone: () => import('@ant-design/icons-vue/es/icons/AppstoreTwoTone.js'),
  ArrowDownOutlined: () => import('@ant-design/icons-vue/es/icons/ArrowDownOutlined.js'),
  ArrowUpOutlined: () => import('@ant-design/icons-vue/es/icons/ArrowUpOutlined.js'),
  ArrowsAltOutlined: () => import('@ant-design/icons-vue/es/icons/ArrowsAltOutlined.js'),
  AudioFilled: () => import('@ant-design/icons-vue/es/icons/AudioFilled.js'),
  AudioMutedOutlined: () => import('@ant-design/icons-vue/es/icons/AudioMutedOutlined.js'),
  AudioOutlined: () => import('@ant-design/icons-vue/es/icons/AudioOutlined.js'),
  AudioTwoTone: () => import('@ant-design/icons-vue/es/icons/AudioTwoTone.js'),
  BackwardFilled: () => import('@ant-design/icons-vue/es/icons/BackwardFilled.js'),
  BackwardOutlined: () => import('@ant-design/icons-vue/es/icons/BackwardOutlined.js'),
  BankFilled: () => import('@ant-design/icons-vue/es/icons/BankFilled.js'),
  BankTwoTone: () => import('@ant-design/icons-vue/es/icons/BankTwoTone.js'),
  BehanceCircleFilled: () => import('@ant-design/icons-vue/es/icons/BehanceCircleFilled.js'),
  BehanceOutlined: () => import('@ant-design/icons-vue/es/icons/BehanceOutlined.js'),
  BehanceSquareFilled: () => import('@ant-design/icons-vue/es/icons/BehanceSquareFilled.js'),
  BehanceSquareOutlined: () => import('@ant-design/icons-vue/es/icons/BehanceSquareOutlined.js'),
  BellFilled: () => import('@ant-design/icons-vue/es/icons/BellFilled.js'),
  BellTwoTone: () => import('@ant-design/icons-vue/es/icons/BellTwoTone.js'),
  BgColorsOutlined: () => import('@ant-design/icons-vue/es/icons/BgColorsOutlined.js'),
  BlockOutlined: () => import('@ant-design/icons-vue/es/icons/BlockOutlined.js'),
  BoldOutlined: () => import('@ant-design/icons-vue/es/icons/BoldOutlined.js'),
  BookFilled: () => import('@ant-design/icons-vue/es/icons/BookFilled.js'),
  BookTwoTone: () => import('@ant-design/icons-vue/es/icons/BookTwoTone.js'),
  BorderBottomOutlined: () => import('@ant-design/icons-vue/es/icons/BorderBottomOutlined.js'),
  BorderHorizontalOutlined: () =>
    import('@ant-design/icons-vue/es/icons/BorderHorizontalOutlined.js'),
  BorderInnerOutlined: () => import('@ant-design/icons-vue/es/icons/BorderInnerOutlined.js'),
  BorderLeftOutlined: () => import('@ant-design/icons-vue/es/icons/BorderLeftOutlined.js'),
  BorderOuterOutlined: () => import('@ant-design/icons-vue/es/icons/BorderOuterOutlined.js'),
  BorderOutlined: () => import('@ant-design/icons-vue/es/icons/BorderOutlined.js'),
  BorderRightOutlined: () => import('@ant-design/icons-vue/es/icons/BorderRightOutlined.js'),
  BorderTopOutlined: () => import('@ant-design/icons-vue/es/icons/BorderTopOutlined.js'),
  BorderVerticleOutlined: () => import('@ant-design/icons-vue/es/icons/BorderVerticleOutlined.js'),
  BorderlessTableOutlined: () =>
    import('@ant-design/icons-vue/es/icons/BorderlessTableOutlined.js'),
  BoxPlotFilled: () => import('@ant-design/icons-vue/es/icons/BoxPlotFilled.js'),
  BoxPlotOutlined: () => import('@ant-design/icons-vue/es/icons/BoxPlotOutlined.js'),
  BoxPlotTwoTone: () => import('@ant-design/icons-vue/es/icons/BoxPlotTwoTone.js'),
  BugFilled: () => import('@ant-design/icons-vue/es/icons/BugFilled.js'),
  BugOutlined: () => import('@ant-design/icons-vue/es/icons/BugOutlined.js'),
  BugTwoTone: () => import('@ant-design/icons-vue/es/icons/BugTwoTone.js'),
  BuildFilled: () => import('@ant-design/icons-vue/es/icons/BuildFilled.js'),
  BuildTwoTone: () => import('@ant-design/icons-vue/es/icons/BuildTwoTone.js'),
  BulbFilled: () => import('@ant-design/icons-vue/es/icons/BulbFilled.js'),
  BulbOutlined: () => import('@ant-design/icons-vue/es/icons/BulbOutlined.js'),
  BulbTwoTone: () => import('@ant-design/icons-vue/es/icons/BulbTwoTone.js'),
  CalculatorFilled: () => import('@ant-design/icons-vue/es/icons/CalculatorFilled.js'),
  CalculatorTwoTone: () => import('@ant-design/icons-vue/es/icons/CalculatorTwoTone.js'),
  CalendarFilled: () => import('@ant-design/icons-vue/es/icons/CalendarFilled.js'),
  CalendarTwoTone: () => import('@ant-design/icons-vue/es/icons/CalendarTwoTone.js'),
  CameraFilled: () => import('@ant-design/icons-vue/es/icons/CameraFilled.js'),
  CameraOutlined: () => import('@ant-design/icons-vue/es/icons/CameraOutlined.js'),
  CameraTwoTone: () => import('@ant-design/icons-vue/es/icons/CameraTwoTone.js'),
  CarFilled: () => import('@ant-design/icons-vue/es/icons/CarFilled.js'),
  CarTwoTone: () => import('@ant-design/icons-vue/es/icons/CarTwoTone.js'),
  CaretLeftFilled: () => import('@ant-design/icons-vue/es/icons/CaretLeftFilled.js'),
  CaretLeftOutlined: () => import('@ant-design/icons-vue/es/icons/CaretLeftOutlined.js'),
  CaretRightFilled: () => import('@ant-design/icons-vue/es/icons/CaretRightFilled.js'),
  CaretRightOutlined: () => import('@ant-design/icons-vue/es/icons/CaretRightOutlined.js'),
  CaretUpFilled: () => import('@ant-design/icons-vue/es/icons/CaretUpFilled.js'),
  CarryOutFilled: () => import('@ant-design/icons-vue/es/icons/CarryOutFilled.js'),
  CarryOutOutlined: () => import('@ant-design/icons-vue/es/icons/CarryOutOutlined.js'),
  CarryOutTwoTone: () => import('@ant-design/icons-vue/es/icons/CarryOutTwoTone.js'),
  CheckCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/CheckCircleTwoTone.js'),
  CheckSquareFilled: () => import('@ant-design/icons-vue/es/icons/CheckSquareFilled.js'),
  CheckSquareOutlined: () => import('@ant-design/icons-vue/es/icons/CheckSquareOutlined.js'),
  CheckSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/CheckSquareTwoTone.js'),
  ChromeFilled: () => import('@ant-design/icons-vue/es/icons/ChromeFilled.js'),
  ChromeOutlined: () => import('@ant-design/icons-vue/es/icons/ChromeOutlined.js'),
  CiCircleFilled: () => import('@ant-design/icons-vue/es/icons/CiCircleFilled.js'),
  CiCircleOutlined: () => import('@ant-design/icons-vue/es/icons/CiCircleOutlined.js'),
  CiCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/CiCircleTwoTone.js'),
  CiOutlined: () => import('@ant-design/icons-vue/es/icons/CiOutlined.js'),
  CiTwoTone: () => import('@ant-design/icons-vue/es/icons/CiTwoTone.js'),
  ClearOutlined: () => import('@ant-design/icons-vue/es/icons/ClearOutlined.js'),
  ClockCircleFilled: () => import('@ant-design/icons-vue/es/icons/ClockCircleFilled.js'),
  ClockCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/ClockCircleTwoTone.js'),
  CloseCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/CloseCircleTwoTone.js'),
  CloseSquareFilled: () => import('@ant-design/icons-vue/es/icons/CloseSquareFilled.js'),
  CloseSquareOutlined: () => import('@ant-design/icons-vue/es/icons/CloseSquareOutlined.js'),
  CloseSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/CloseSquareTwoTone.js'),
  CloudDownloadOutlined: () => import('@ant-design/icons-vue/es/icons/CloudDownloadOutlined.js'),
  CloudFilled: () => import('@ant-design/icons-vue/es/icons/CloudFilled.js'),
  CloudOutlined: () => import('@ant-design/icons-vue/es/icons/CloudOutlined.js'),
  CloudSyncOutlined: () => import('@ant-design/icons-vue/es/icons/CloudSyncOutlined.js'),
  CloudTwoTone: () => import('@ant-design/icons-vue/es/icons/CloudTwoTone.js'),
  CloudUploadOutlined: () => import('@ant-design/icons-vue/es/icons/CloudUploadOutlined.js'),
  CodeFilled: () => import('@ant-design/icons-vue/es/icons/CodeFilled.js'),
  CodeOutlined: () => import('@ant-design/icons-vue/es/icons/CodeOutlined.js'),
  CodeSandboxCircleFilled: () =>
    import('@ant-design/icons-vue/es/icons/CodeSandboxCircleFilled.js'),
  CodeSandboxSquareFilled: () =>
    import('@ant-design/icons-vue/es/icons/CodeSandboxSquareFilled.js'),
  CodeTwoTone: () => import('@ant-design/icons-vue/es/icons/CodeTwoTone.js'),
  CodepenCircleFilled: () => import('@ant-design/icons-vue/es/icons/CodepenCircleFilled.js'),
  CodepenCircleOutlined: () => import('@ant-design/icons-vue/es/icons/CodepenCircleOutlined.js'),
  CodepenOutlined: () => import('@ant-design/icons-vue/es/icons/CodepenOutlined.js'),
  CodepenSquareFilled: () => import('@ant-design/icons-vue/es/icons/CodepenSquareFilled.js'),
  CoffeeOutlined: () => import('@ant-design/icons-vue/es/icons/CoffeeOutlined.js'),
  CommentOutlined: () => import('@ant-design/icons-vue/es/icons/CommentOutlined.js'),
  CompassFilled: () => import('@ant-design/icons-vue/es/icons/CompassFilled.js'),
  CompassOutlined: () => import('@ant-design/icons-vue/es/icons/CompassOutlined.js'),
  CompassTwoTone: () => import('@ant-design/icons-vue/es/icons/CompassTwoTone.js'),
  CompressOutlined: () => import('@ant-design/icons-vue/es/icons/CompressOutlined.js'),
  ConsoleSqlOutlined: () => import('@ant-design/icons-vue/es/icons/ConsoleSqlOutlined.js'),
  ContactsFilled: () => import('@ant-design/icons-vue/es/icons/ContactsFilled.js'),
  ContactsOutlined: () => import('@ant-design/icons-vue/es/icons/ContactsOutlined.js'),
  ContactsTwoTone: () => import('@ant-design/icons-vue/es/icons/ContactsTwoTone.js'),
  ContainerFilled: () => import('@ant-design/icons-vue/es/icons/ContainerFilled.js'),
  ContainerTwoTone: () => import('@ant-design/icons-vue/es/icons/ContainerTwoTone.js'),
  ControlFilled: () => import('@ant-design/icons-vue/es/icons/ControlFilled.js'),
  ControlTwoTone: () => import('@ant-design/icons-vue/es/icons/ControlTwoTone.js'),
  CopyFilled: () => import('@ant-design/icons-vue/es/icons/CopyFilled.js'),
  CopyTwoTone: () => import('@ant-design/icons-vue/es/icons/CopyTwoTone.js'),
  CopyrightCircleFilled: () => import('@ant-design/icons-vue/es/icons/CopyrightCircleFilled.js'),
  CopyrightCircleOutlined: () =>
    import('@ant-design/icons-vue/es/icons/CopyrightCircleOutlined.js'),
  CopyrightCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/CopyrightCircleTwoTone.js'),
  CopyrightOutlined: () => import('@ant-design/icons-vue/es/icons/CopyrightOutlined.js'),
  CopyrightTwoTone: () => import('@ant-design/icons-vue/es/icons/CopyrightTwoTone.js'),
  CreditCardFilled: () => import('@ant-design/icons-vue/es/icons/CreditCardFilled.js'),
  CreditCardTwoTone: () => import('@ant-design/icons-vue/es/icons/CreditCardTwoTone.js'),
  CrownFilled: () => import('@ant-design/icons-vue/es/icons/CrownFilled.js'),
  CrownOutlined: () => import('@ant-design/icons-vue/es/icons/CrownOutlined.js'),
  CrownTwoTone: () => import('@ant-design/icons-vue/es/icons/CrownTwoTone.js'),
  CustomerServiceFilled: () => import('@ant-design/icons-vue/es/icons/CustomerServiceFilled.js'),
  CustomerServiceOutlined: () =>
    import('@ant-design/icons-vue/es/icons/CustomerServiceOutlined.js'),
  CustomerServiceTwoTone: () => import('@ant-design/icons-vue/es/icons/CustomerServiceTwoTone.js'),
  DashOutlined: () => import('@ant-design/icons-vue/es/icons/DashOutlined.js'),
  DashboardFilled: () => import('@ant-design/icons-vue/es/icons/DashboardFilled.js'),
  DashboardTwoTone: () => import('@ant-design/icons-vue/es/icons/DashboardTwoTone.js'),
  DatabaseFilled: () => import('@ant-design/icons-vue/es/icons/DatabaseFilled.js'),
  DatabaseTwoTone: () => import('@ant-design/icons-vue/es/icons/DatabaseTwoTone.js'),
  DeleteColumnOutlined: () => import('@ant-design/icons-vue/es/icons/DeleteColumnOutlined.js'),
  DeleteFilled: () => import('@ant-design/icons-vue/es/icons/DeleteFilled.js'),
  DeleteRowOutlined: () => import('@ant-design/icons-vue/es/icons/DeleteRowOutlined.js'),
  DeleteTwoTone: () => import('@ant-design/icons-vue/es/icons/DeleteTwoTone.js'),
  DeliveredProcedureOutlined: () =>
    import('@ant-design/icons-vue/es/icons/DeliveredProcedureOutlined.js'),
  DesktopOutlined: () => import('@ant-design/icons-vue/es/icons/DesktopOutlined.js'),
  DiffFilled: () => import('@ant-design/icons-vue/es/icons/DiffFilled.js'),
  DiffOutlined: () => import('@ant-design/icons-vue/es/icons/DiffOutlined.js'),
  DiffTwoTone: () => import('@ant-design/icons-vue/es/icons/DiffTwoTone.js'),
  DingdingOutlined: () => import('@ant-design/icons-vue/es/icons/DingdingOutlined.js'),
  DingtalkCircleFilled: () => import('@ant-design/icons-vue/es/icons/DingtalkCircleFilled.js'),
  DingtalkOutlined: () => import('@ant-design/icons-vue/es/icons/DingtalkOutlined.js'),
  DingtalkSquareFilled: () => import('@ant-design/icons-vue/es/icons/DingtalkSquareFilled.js'),
  DisconnectOutlined: () => import('@ant-design/icons-vue/es/icons/DisconnectOutlined.js'),
  DislikeFilled: () => import('@ant-design/icons-vue/es/icons/DislikeFilled.js'),
  DislikeOutlined: () => import('@ant-design/icons-vue/es/icons/DislikeOutlined.js'),
  DislikeTwoTone: () => import('@ant-design/icons-vue/es/icons/DislikeTwoTone.js'),
  DollarCircleFilled: () => import('@ant-design/icons-vue/es/icons/DollarCircleFilled.js'),
  DollarCircleOutlined: () => import('@ant-design/icons-vue/es/icons/DollarCircleOutlined.js'),
  DollarCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/DollarCircleTwoTone.js'),
  DollarTwoTone: () => import('@ant-design/icons-vue/es/icons/DollarTwoTone.js'),
  DotChartOutlined: () => import('@ant-design/icons-vue/es/icons/DotChartOutlined.js'),
  DownCircleFilled: () => import('@ant-design/icons-vue/es/icons/DownCircleFilled.js'),
  DownCircleOutlined: () => import('@ant-design/icons-vue/es/icons/DownCircleOutlined.js'),
  DownCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/DownCircleTwoTone.js'),
  DownSquareFilled: () => import('@ant-design/icons-vue/es/icons/DownSquareFilled.js'),
  DownSquareOutlined: () => import('@ant-design/icons-vue/es/icons/DownSquareOutlined.js'),
  DownSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/DownSquareTwoTone.js'),
  DragOutlined: () => import('@ant-design/icons-vue/es/icons/DragOutlined.js'),
  DribbbleCircleFilled: () => import('@ant-design/icons-vue/es/icons/DribbbleCircleFilled.js'),
  DribbbleOutlined: () => import('@ant-design/icons-vue/es/icons/DribbbleOutlined.js'),
  DribbbleSquareFilled: () => import('@ant-design/icons-vue/es/icons/DribbbleSquareFilled.js'),
  DribbbleSquareOutlined: () => import('@ant-design/icons-vue/es/icons/DribbbleSquareOutlined.js'),
  DropboxCircleFilled: () => import('@ant-design/icons-vue/es/icons/DropboxCircleFilled.js'),
  DropboxSquareFilled: () => import('@ant-design/icons-vue/es/icons/DropboxSquareFilled.js'),
  EditFilled: () => import('@ant-design/icons-vue/es/icons/EditFilled.js'),
  EditTwoTone: () => import('@ant-design/icons-vue/es/icons/EditTwoTone.js'),
  EnvironmentFilled: () => import('@ant-design/icons-vue/es/icons/EnvironmentFilled.js'),
  EnvironmentTwoTone: () => import('@ant-design/icons-vue/es/icons/EnvironmentTwoTone.js'),
  EuroCircleFilled: () => import('@ant-design/icons-vue/es/icons/EuroCircleFilled.js'),
  EuroCircleOutlined: () => import('@ant-design/icons-vue/es/icons/EuroCircleOutlined.js'),
  EuroCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/EuroCircleTwoTone.js'),
  EuroOutlined: () => import('@ant-design/icons-vue/es/icons/EuroOutlined.js'),
  EuroTwoTone: () => import('@ant-design/icons-vue/es/icons/EuroTwoTone.js'),
  ExceptionOutlined: () => import('@ant-design/icons-vue/es/icons/ExceptionOutlined.js'),
  ExclamationCircleTwoTone: () =>
    import('@ant-design/icons-vue/es/icons/ExclamationCircleTwoTone.js'),
  ExclamationOutlined: () => import('@ant-design/icons-vue/es/icons/ExclamationOutlined.js'),
  ExpandAltOutlined: () => import('@ant-design/icons-vue/es/icons/ExpandAltOutlined.js'),
  ExpandOutlined: () => import('@ant-design/icons-vue/es/icons/ExpandOutlined.js'),
  ExperimentFilled: () => import('@ant-design/icons-vue/es/icons/ExperimentFilled.js'),
  ExperimentOutlined: () => import('@ant-design/icons-vue/es/icons/ExperimentOutlined.js'),
  ExperimentTwoTone: () => import('@ant-design/icons-vue/es/icons/ExperimentTwoTone.js'),
  EyeFilled: () => import('@ant-design/icons-vue/es/icons/EyeFilled.js'),
  EyeInvisibleFilled: () => import('@ant-design/icons-vue/es/icons/EyeInvisibleFilled.js'),
  EyeInvisibleTwoTone: () => import('@ant-design/icons-vue/es/icons/EyeInvisibleTwoTone.js'),
  EyeTwoTone: () => import('@ant-design/icons-vue/es/icons/EyeTwoTone.js'),
  FacebookFilled: () => import('@ant-design/icons-vue/es/icons/FacebookFilled.js'),
  FacebookOutlined: () => import('@ant-design/icons-vue/es/icons/FacebookOutlined.js'),
  FastBackwardFilled: () => import('@ant-design/icons-vue/es/icons/FastBackwardFilled.js'),
  FastBackwardOutlined: () => import('@ant-design/icons-vue/es/icons/FastBackwardOutlined.js'),
  FastForwardFilled: () => import('@ant-design/icons-vue/es/icons/FastForwardFilled.js'),
  FastForwardOutlined: () => import('@ant-design/icons-vue/es/icons/FastForwardOutlined.js'),
  FieldBinaryOutlined: () => import('@ant-design/icons-vue/es/icons/FieldBinaryOutlined.js'),
  FieldStringOutlined: () => import('@ant-design/icons-vue/es/icons/FieldStringOutlined.js'),
  FieldTimeOutlined: () => import('@ant-design/icons-vue/es/icons/FieldTimeOutlined.js'),
  FileAddFilled: () => import('@ant-design/icons-vue/es/icons/FileAddFilled.js'),
  FileAddOutlined: () => import('@ant-design/icons-vue/es/icons/FileAddOutlined.js'),
  FileAddTwoTone: () => import('@ant-design/icons-vue/es/icons/FileAddTwoTone.js'),
  FileExcelFilled: () => import('@ant-design/icons-vue/es/icons/FileExcelFilled.js'),
  FileExcelOutlined: () => import('@ant-design/icons-vue/es/icons/FileExcelOutlined.js'),
  FileExcelTwoTone: () => import('@ant-design/icons-vue/es/icons/FileExcelTwoTone.js'),
  FileExclamationFilled: () => import('@ant-design/icons-vue/es/icons/FileExclamationFilled.js'),
  FileExclamationOutlined: () =>
    import('@ant-design/icons-vue/es/icons/FileExclamationOutlined.js'),
  FileExclamationTwoTone: () => import('@ant-design/icons-vue/es/icons/FileExclamationTwoTone.js'),
  FileFilled: () => import('@ant-design/icons-vue/es/icons/FileFilled.js'),
  FileGifOutlined: () => import('@ant-design/icons-vue/es/icons/FileGifOutlined.js'),
  FileImageFilled: () => import('@ant-design/icons-vue/es/icons/FileImageFilled.js'),
  FileImageOutlined: () => import('@ant-design/icons-vue/es/icons/FileImageOutlined.js'),
  FileImageTwoTone: () => import('@ant-design/icons-vue/es/icons/FileImageTwoTone.js'),
  FileJpgOutlined: () => import('@ant-design/icons-vue/es/icons/FileJpgOutlined.js'),
  FileMarkdownFilled: () => import('@ant-design/icons-vue/es/icons/FileMarkdownFilled.js'),
  FileMarkdownOutlined: () => import('@ant-design/icons-vue/es/icons/FileMarkdownOutlined.js'),
  FileMarkdownTwoTone: () => import('@ant-design/icons-vue/es/icons/FileMarkdownTwoTone.js'),
  FilePdfFilled: () => import('@ant-design/icons-vue/es/icons/FilePdfFilled.js'),
  FilePdfOutlined: () => import('@ant-design/icons-vue/es/icons/FilePdfOutlined.js'),
  FilePdfTwoTone: () => import('@ant-design/icons-vue/es/icons/FilePdfTwoTone.js'),
  FilePptFilled: () => import('@ant-design/icons-vue/es/icons/FilePptFilled.js'),
  FilePptOutlined: () => import('@ant-design/icons-vue/es/icons/FilePptOutlined.js'),
  FilePptTwoTone: () => import('@ant-design/icons-vue/es/icons/FilePptTwoTone.js'),
  FileTextFilled: () => import('@ant-design/icons-vue/es/icons/FileTextFilled.js'),
  FileTextTwoTone: () => import('@ant-design/icons-vue/es/icons/FileTextTwoTone.js'),
  FileUnknownFilled: () => import('@ant-design/icons-vue/es/icons/FileUnknownFilled.js'),
  FileUnknownOutlined: () => import('@ant-design/icons-vue/es/icons/FileUnknownOutlined.js'),
  FileUnknownTwoTone: () => import('@ant-design/icons-vue/es/icons/FileUnknownTwoTone.js'),
  FileWordFilled: () => import('@ant-design/icons-vue/es/icons/FileWordFilled.js'),
  FileWordOutlined: () => import('@ant-design/icons-vue/es/icons/FileWordOutlined.js'),
  FileWordTwoTone: () => import('@ant-design/icons-vue/es/icons/FileWordTwoTone.js'),
  FileZipFilled: () => import('@ant-design/icons-vue/es/icons/FileZipFilled.js'),
  FileZipOutlined: () => import('@ant-design/icons-vue/es/icons/FileZipOutlined.js'),
  FileZipTwoTone: () => import('@ant-design/icons-vue/es/icons/FileZipTwoTone.js'),
  FilterOutlined: () => import('@ant-design/icons-vue/es/icons/FilterOutlined.js'),
  FilterTwoTone: () => import('@ant-design/icons-vue/es/icons/FilterTwoTone.js'),
  FireFilled: () => import('@ant-design/icons-vue/es/icons/FireFilled.js'),
  FireOutlined: () => import('@ant-design/icons-vue/es/icons/FireOutlined.js'),
  FireTwoTone: () => import('@ant-design/icons-vue/es/icons/FireTwoTone.js'),
  FlagFilled: () => import('@ant-design/icons-vue/es/icons/FlagFilled.js'),
  FlagOutlined: () => import('@ant-design/icons-vue/es/icons/FlagOutlined.js'),
  FlagTwoTone: () => import('@ant-design/icons-vue/es/icons/FlagTwoTone.js'),
  FolderAddFilled: () => import('@ant-design/icons-vue/es/icons/FolderAddFilled.js'),
  FolderAddOutlined: () => import('@ant-design/icons-vue/es/icons/FolderAddOutlined.js'),
  FolderAddTwoTone: () => import('@ant-design/icons-vue/es/icons/FolderAddTwoTone.js'),
  FolderFilled: () => import('@ant-design/icons-vue/es/icons/FolderFilled.js'),
  FolderOpenFilled: () => import('@ant-design/icons-vue/es/icons/FolderOpenFilled.js'),
  FolderOpenTwoTone: () => import('@ant-design/icons-vue/es/icons/FolderOpenTwoTone.js'),
  FolderTwoTone: () => import('@ant-design/icons-vue/es/icons/FolderTwoTone.js'),
  FolderViewOutlined: () => import('@ant-design/icons-vue/es/icons/FolderViewOutlined.js'),
  FontColorsOutlined: () => import('@ant-design/icons-vue/es/icons/FontColorsOutlined.js'),
  FontSizeOutlined: () => import('@ant-design/icons-vue/es/icons/FontSizeOutlined.js'),
  FormOutlined: () => import('@ant-design/icons-vue/es/icons/FormOutlined.js'),
  FormatPainterFilled: () => import('@ant-design/icons-vue/es/icons/FormatPainterFilled.js'),
  FormatPainterOutlined: () => import('@ant-design/icons-vue/es/icons/FormatPainterOutlined.js'),
  ForwardFilled: () => import('@ant-design/icons-vue/es/icons/ForwardFilled.js'),
  ForwardOutlined: () => import('@ant-design/icons-vue/es/icons/ForwardOutlined.js'),
  FrownFilled: () => import('@ant-design/icons-vue/es/icons/FrownFilled.js'),
  FrownOutlined: () => import('@ant-design/icons-vue/es/icons/FrownOutlined.js'),
  FrownTwoTone: () => import('@ant-design/icons-vue/es/icons/FrownTwoTone.js'),
  FullscreenExitOutlined: () => import('@ant-design/icons-vue/es/icons/FullscreenExitOutlined.js'),
  FullscreenOutlined: () => import('@ant-design/icons-vue/es/icons/FullscreenOutlined.js'),
  FunctionOutlined: () => import('@ant-design/icons-vue/es/icons/FunctionOutlined.js'),
  FundFilled: () => import('@ant-design/icons-vue/es/icons/FundFilled.js'),
  FundProjectionScreenOutlined: () =>
    import('@ant-design/icons-vue/es/icons/FundProjectionScreenOutlined.js'),
  FundTwoTone: () => import('@ant-design/icons-vue/es/icons/FundTwoTone.js'),
  FundViewOutlined: () => import('@ant-design/icons-vue/es/icons/FundViewOutlined.js'),
  FunnelPlotFilled: () => import('@ant-design/icons-vue/es/icons/FunnelPlotFilled.js'),
  FunnelPlotOutlined: () => import('@ant-design/icons-vue/es/icons/FunnelPlotOutlined.js'),
  FunnelPlotTwoTone: () => import('@ant-design/icons-vue/es/icons/FunnelPlotTwoTone.js'),
  GifOutlined: () => import('@ant-design/icons-vue/es/icons/GifOutlined.js'),
  GiftFilled: () => import('@ant-design/icons-vue/es/icons/GiftFilled.js'),
  GiftOutlined: () => import('@ant-design/icons-vue/es/icons/GiftOutlined.js'),
  GiftTwoTone: () => import('@ant-design/icons-vue/es/icons/GiftTwoTone.js'),
  GithubFilled: () => import('@ant-design/icons-vue/es/icons/GithubFilled.js'),
  GithubOutlined: () => import('@ant-design/icons-vue/es/icons/GithubOutlined.js'),
  GitlabFilled: () => import('@ant-design/icons-vue/es/icons/GitlabFilled.js'),
  GitlabOutlined: () => import('@ant-design/icons-vue/es/icons/GitlabOutlined.js'),
  GoldFilled: () => import('@ant-design/icons-vue/es/icons/GoldFilled.js'),
  GoldTwoTone: () => import('@ant-design/icons-vue/es/icons/GoldTwoTone.js'),
  GoldenFilled: () => import('@ant-design/icons-vue/es/icons/GoldenFilled.js'),
  GoogleCircleFilled: () => import('@ant-design/icons-vue/es/icons/GoogleCircleFilled.js'),
  GoogleOutlined: () => import('@ant-design/icons-vue/es/icons/GoogleOutlined.js'),
  GooglePlusCircleFilled: () => import('@ant-design/icons-vue/es/icons/GooglePlusCircleFilled.js'),
  GooglePlusOutlined: () => import('@ant-design/icons-vue/es/icons/GooglePlusOutlined.js'),
  GooglePlusSquareFilled: () => import('@ant-design/icons-vue/es/icons/GooglePlusSquareFilled.js'),
  GoogleSquareFilled: () => import('@ant-design/icons-vue/es/icons/GoogleSquareFilled.js'),
  GroupOutlined: () => import('@ant-design/icons-vue/es/icons/GroupOutlined.js'),
  HddFilled: () => import('@ant-design/icons-vue/es/icons/HddFilled.js'),
  HddTwoTone: () => import('@ant-design/icons-vue/es/icons/HddTwoTone.js'),
  HeartFilled: () => import('@ant-design/icons-vue/es/icons/HeartFilled.js'),
  HeartOutlined: () => import('@ant-design/icons-vue/es/icons/HeartOutlined.js'),
  HeartTwoTone: () => import('@ant-design/icons-vue/es/icons/HeartTwoTone.js'),
  HeatMapOutlined: () => import('@ant-design/icons-vue/es/icons/HeatMapOutlined.js'),
  HighlightFilled: () => import('@ant-design/icons-vue/es/icons/HighlightFilled.js'),
  HighlightOutlined: () => import('@ant-design/icons-vue/es/icons/HighlightOutlined.js'),
  HighlightTwoTone: () => import('@ant-design/icons-vue/es/icons/HighlightTwoTone.js'),
  HolderOutlined: () => import('@ant-design/icons-vue/es/icons/HolderOutlined.js'),
  HomeFilled: () => import('@ant-design/icons-vue/es/icons/HomeFilled.js'),
  HomeTwoTone: () => import('@ant-design/icons-vue/es/icons/HomeTwoTone.js'),
  HourglassFilled: () => import('@ant-design/icons-vue/es/icons/HourglassFilled.js'),
  HourglassOutlined: () => import('@ant-design/icons-vue/es/icons/HourglassOutlined.js'),
  HourglassTwoTone: () => import('@ant-design/icons-vue/es/icons/HourglassTwoTone.js'),
  Html5Filled: () => import('@ant-design/icons-vue/es/icons/Html5Filled.js'),
  Html5Outlined: () => import('@ant-design/icons-vue/es/icons/Html5Outlined.js'),
  Html5TwoTone: () => import('@ant-design/icons-vue/es/icons/Html5TwoTone.js'),
  IdcardFilled: () => import('@ant-design/icons-vue/es/icons/IdcardFilled.js'),
  IdcardOutlined: () => import('@ant-design/icons-vue/es/icons/IdcardOutlined.js'),
  IdcardTwoTone: () => import('@ant-design/icons-vue/es/icons/IdcardTwoTone.js'),
  IeCircleFilled: () => import('@ant-design/icons-vue/es/icons/IeCircleFilled.js'),
  IeOutlined: () => import('@ant-design/icons-vue/es/icons/IeOutlined.js'),
  IeSquareFilled: () => import('@ant-design/icons-vue/es/icons/IeSquareFilled.js'),
  InfoCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/InfoCircleTwoTone.js'),
  InfoOutlined: () => import('@ant-design/icons-vue/es/icons/InfoOutlined.js'),
  InsertRowAboveOutlined: () => import('@ant-design/icons-vue/es/icons/InsertRowAboveOutlined.js'),
  InsertRowBelowOutlined: () => import('@ant-design/icons-vue/es/icons/InsertRowBelowOutlined.js'),
  InsertRowLeftOutlined: () => import('@ant-design/icons-vue/es/icons/InsertRowLeftOutlined.js'),
  InsertRowRightOutlined: () => import('@ant-design/icons-vue/es/icons/InsertRowRightOutlined.js'),
  InstagramFilled: () => import('@ant-design/icons-vue/es/icons/InstagramFilled.js'),
  InstagramOutlined: () => import('@ant-design/icons-vue/es/icons/InstagramOutlined.js'),
  InsuranceFilled: () => import('@ant-design/icons-vue/es/icons/InsuranceFilled.js'),
  InsuranceOutlined: () => import('@ant-design/icons-vue/es/icons/InsuranceOutlined.js'),
  InsuranceTwoTone: () => import('@ant-design/icons-vue/es/icons/InsuranceTwoTone.js'),
  InteractionFilled: () => import('@ant-design/icons-vue/es/icons/InteractionFilled.js'),
  InteractionOutlined: () => import('@ant-design/icons-vue/es/icons/InteractionOutlined.js'),
  InteractionTwoTone: () => import('@ant-design/icons-vue/es/icons/InteractionTwoTone.js'),
  IssuesCloseOutlined: () => import('@ant-design/icons-vue/es/icons/IssuesCloseOutlined.js'),
  ItalicOutlined: () => import('@ant-design/icons-vue/es/icons/ItalicOutlined.js'),
  LaptopOutlined: () => import('@ant-design/icons-vue/es/icons/LaptopOutlined.js'),
  LayoutFilled: () => import('@ant-design/icons-vue/es/icons/LayoutFilled.js'),
  LayoutTwoTone: () => import('@ant-design/icons-vue/es/icons/LayoutTwoTone.js'),
  LeftCircleFilled: () => import('@ant-design/icons-vue/es/icons/LeftCircleFilled.js'),
  LeftCircleOutlined: () => import('@ant-design/icons-vue/es/icons/LeftCircleOutlined.js'),
  LeftCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/LeftCircleTwoTone.js'),
  LeftSquareFilled: () => import('@ant-design/icons-vue/es/icons/LeftSquareFilled.js'),
  LeftSquareOutlined: () => import('@ant-design/icons-vue/es/icons/LeftSquareOutlined.js'),
  LeftSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/LeftSquareTwoTone.js'),
  LikeFilled: () => import('@ant-design/icons-vue/es/icons/LikeFilled.js'),
  LikeOutlined: () => import('@ant-design/icons-vue/es/icons/LikeOutlined.js'),
  LikeTwoTone: () => import('@ant-design/icons-vue/es/icons/LikeTwoTone.js'),
  LineHeightOutlined: () => import('@ant-design/icons-vue/es/icons/LineHeightOutlined.js'),
  LineOutlined: () => import('@ant-design/icons-vue/es/icons/LineOutlined.js'),
  LinkOutlined: () => import('@ant-design/icons-vue/es/icons/LinkOutlined.js'),
  LinkedinFilled: () => import('@ant-design/icons-vue/es/icons/LinkedinFilled.js'),
  LinkedinOutlined: () => import('@ant-design/icons-vue/es/icons/LinkedinOutlined.js'),
  Loading3QuartersOutlined: () =>
    import('@ant-design/icons-vue/es/icons/Loading3QuartersOutlined.js'),
  LockFilled: () => import('@ant-design/icons-vue/es/icons/LockFilled.js'),
  LockTwoTone: () => import('@ant-design/icons-vue/es/icons/LockTwoTone.js'),
  LoginOutlined: () => import('@ant-design/icons-vue/es/icons/LoginOutlined.js'),
  LogoutOutlined: () => import('@ant-design/icons-vue/es/icons/LogoutOutlined.js'),
  MacCommandFilled: () => import('@ant-design/icons-vue/es/icons/MacCommandFilled.js'),
  MacCommandOutlined: () => import('@ant-design/icons-vue/es/icons/MacCommandOutlined.js'),
  MailFilled: () => import('@ant-design/icons-vue/es/icons/MailFilled.js'),
  MailOutlined: () => import('@ant-design/icons-vue/es/icons/MailOutlined.js'),
  MailTwoTone: () => import('@ant-design/icons-vue/es/icons/MailTwoTone.js'),
  ManOutlined: () => import('@ant-design/icons-vue/es/icons/ManOutlined.js'),
  MedicineBoxFilled: () => import('@ant-design/icons-vue/es/icons/MedicineBoxFilled.js'),
  MedicineBoxOutlined: () => import('@ant-design/icons-vue/es/icons/MedicineBoxOutlined.js'),
  MedicineBoxTwoTone: () => import('@ant-design/icons-vue/es/icons/MedicineBoxTwoTone.js'),
  MediumCircleFilled: () => import('@ant-design/icons-vue/es/icons/MediumCircleFilled.js'),
  MediumOutlined: () => import('@ant-design/icons-vue/es/icons/MediumOutlined.js'),
  MediumSquareFilled: () => import('@ant-design/icons-vue/es/icons/MediumSquareFilled.js'),
  MediumWorkmarkOutlined: () => import('@ant-design/icons-vue/es/icons/MediumWorkmarkOutlined.js'),
  MehFilled: () => import('@ant-design/icons-vue/es/icons/MehFilled.js'),
  MehOutlined: () => import('@ant-design/icons-vue/es/icons/MehOutlined.js'),
  MehTwoTone: () => import('@ant-design/icons-vue/es/icons/MehTwoTone.js'),
  MergeCellsOutlined: () => import('@ant-design/icons-vue/es/icons/MergeCellsOutlined.js'),
  MessageFilled: () => import('@ant-design/icons-vue/es/icons/MessageFilled.js'),
  MessageOutlined: () => import('@ant-design/icons-vue/es/icons/MessageOutlined.js'),
  MessageTwoTone: () => import('@ant-design/icons-vue/es/icons/MessageTwoTone.js'),
  MinusCircleFilled: () => import('@ant-design/icons-vue/es/icons/MinusCircleFilled.js'),
  MinusCircleOutlined: () => import('@ant-design/icons-vue/es/icons/MinusCircleOutlined.js'),
  MinusCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/MinusCircleTwoTone.js'),
  MinusOutlined: () => import('@ant-design/icons-vue/es/icons/MinusOutlined.js'),
  MinusSquareFilled: () => import('@ant-design/icons-vue/es/icons/MinusSquareFilled.js'),
  MinusSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/MinusSquareTwoTone.js'),
  MobileFilled: () => import('@ant-design/icons-vue/es/icons/MobileFilled.js'),
  MobileOutlined: () => import('@ant-design/icons-vue/es/icons/MobileOutlined.js'),
  MobileTwoTone: () => import('@ant-design/icons-vue/es/icons/MobileTwoTone.js'),
  MoneyCollectFilled: () => import('@ant-design/icons-vue/es/icons/MoneyCollectFilled.js'),
  MoneyCollectOutlined: () => import('@ant-design/icons-vue/es/icons/MoneyCollectOutlined.js'),
  MoneyCollectTwoTone: () => import('@ant-design/icons-vue/es/icons/MoneyCollectTwoTone.js'),
  MonitorOutlined: () => import('@ant-design/icons-vue/es/icons/MonitorOutlined.js'),
  MoreOutlined: () => import('@ant-design/icons-vue/es/icons/MoreOutlined.js'),
  NodeCollapseOutlined: () => import('@ant-design/icons-vue/es/icons/NodeCollapseOutlined.js'),
  NodeExpandOutlined: () => import('@ant-design/icons-vue/es/icons/NodeExpandOutlined.js'),
  NotificationFilled: () => import('@ant-design/icons-vue/es/icons/NotificationFilled.js'),
  NotificationOutlined: () => import('@ant-design/icons-vue/es/icons/NotificationOutlined.js'),
  NotificationTwoTone: () => import('@ant-design/icons-vue/es/icons/NotificationTwoTone.js'),
  OneToOneOutlined: () => import('@ant-design/icons-vue/es/icons/OneToOneOutlined.js'),
  OrderedListOutlined: () => import('@ant-design/icons-vue/es/icons/OrderedListOutlined.js'),
  PauseCircleFilled: () => import('@ant-design/icons-vue/es/icons/PauseCircleFilled.js'),
  PauseCircleOutlined: () => import('@ant-design/icons-vue/es/icons/PauseCircleOutlined.js'),
  PauseCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/PauseCircleTwoTone.js'),
  PauseOutlined: () => import('@ant-design/icons-vue/es/icons/PauseOutlined.js'),
  PayCircleFilled: () => import('@ant-design/icons-vue/es/icons/PayCircleFilled.js'),
  PercentageOutlined: () => import('@ant-design/icons-vue/es/icons/PercentageOutlined.js'),
  PhoneFilled: () => import('@ant-design/icons-vue/es/icons/PhoneFilled.js'),
  PhoneOutlined: () => import('@ant-design/icons-vue/es/icons/PhoneOutlined.js'),
  PhoneTwoTone: () => import('@ant-design/icons-vue/es/icons/PhoneTwoTone.js'),
  PicCenterOutlined: () => import('@ant-design/icons-vue/es/icons/PicCenterOutlined.js'),
  PicLeftOutlined: () => import('@ant-design/icons-vue/es/icons/PicLeftOutlined.js'),
  PicRightOutlined: () => import('@ant-design/icons-vue/es/icons/PicRightOutlined.js'),
  PictureFilled: () => import('@ant-design/icons-vue/es/icons/PictureFilled.js'),
  PictureOutlined: () => import('@ant-design/icons-vue/es/icons/PictureOutlined.js'),
  PieChartFilled: () => import('@ant-design/icons-vue/es/icons/PieChartFilled.js'),
  PieChartTwoTone: () => import('@ant-design/icons-vue/es/icons/PieChartTwoTone.js'),
  PlayCircleFilled: () => import('@ant-design/icons-vue/es/icons/PlayCircleFilled.js'),
  PlayCircleOutlined: () => import('@ant-design/icons-vue/es/icons/PlayCircleOutlined.js'),
  PlayCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/PlayCircleTwoTone.js'),
  PlaySquareFilled: () => import('@ant-design/icons-vue/es/icons/PlaySquareFilled.js'),
  PlaySquareOutlined: () => import('@ant-design/icons-vue/es/icons/PlaySquareOutlined.js'),
  PlaySquareTwoTone: () => import('@ant-design/icons-vue/es/icons/PlaySquareTwoTone.js'),
  PlusCircleFilled: () => import('@ant-design/icons-vue/es/icons/PlusCircleFilled.js'),
  PlusCircleOutlined: () => import('@ant-design/icons-vue/es/icons/PlusCircleOutlined.js'),
  PlusCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/PlusCircleTwoTone.js'),
  PlusSquareFilled: () => import('@ant-design/icons-vue/es/icons/PlusSquareFilled.js'),
  PlusSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/PlusSquareTwoTone.js'),
  PoundCircleFilled: () => import('@ant-design/icons-vue/es/icons/PoundCircleFilled.js'),
  PoundCircleOutlined: () => import('@ant-design/icons-vue/es/icons/PoundCircleOutlined.js'),
  PoundCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/PoundCircleTwoTone.js'),
  PoundOutlined: () => import('@ant-design/icons-vue/es/icons/PoundOutlined.js'),
  PoweroffOutlined: () => import('@ant-design/icons-vue/es/icons/PoweroffOutlined.js'),
  PrinterFilled: () => import('@ant-design/icons-vue/es/icons/PrinterFilled.js'),
  PrinterOutlined: () => import('@ant-design/icons-vue/es/icons/PrinterOutlined.js'),
  PrinterTwoTone: () => import('@ant-design/icons-vue/es/icons/PrinterTwoTone.js'),
  ProfileFilled: () => import('@ant-design/icons-vue/es/icons/ProfileFilled.js'),
  ProfileTwoTone: () => import('@ant-design/icons-vue/es/icons/ProfileTwoTone.js'),
  ProjectFilled: () => import('@ant-design/icons-vue/es/icons/ProjectFilled.js'),
  ProjectOutlined: () => import('@ant-design/icons-vue/es/icons/ProjectOutlined.js'),
  ProjectTwoTone: () => import('@ant-design/icons-vue/es/icons/ProjectTwoTone.js'),
  PropertySafetyFilled: () => import('@ant-design/icons-vue/es/icons/PropertySafetyFilled.js'),
  PropertySafetyOutlined: () => import('@ant-design/icons-vue/es/icons/PropertySafetyOutlined.js'),
  PropertySafetyTwoTone: () => import('@ant-design/icons-vue/es/icons/PropertySafetyTwoTone.js'),
  PullRequestOutlined: () => import('@ant-design/icons-vue/es/icons/PullRequestOutlined.js'),
  PushpinFilled: () => import('@ant-design/icons-vue/es/icons/PushpinFilled.js'),
  PushpinOutlined: () => import('@ant-design/icons-vue/es/icons/PushpinOutlined.js'),
  PushpinTwoTone: () => import('@ant-design/icons-vue/es/icons/PushpinTwoTone.js'),
  QqCircleFilled: () => import('@ant-design/icons-vue/es/icons/QqCircleFilled.js'),
  QqOutlined: () => import('@ant-design/icons-vue/es/icons/QqOutlined.js'),
  QqSquareFilled: () => import('@ant-design/icons-vue/es/icons/QqSquareFilled.js'),
  QuestionCircleFilled: () => import('@ant-design/icons-vue/es/icons/QuestionCircleFilled.js'),
  QuestionCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/QuestionCircleTwoTone.js'),
  QuestionOutlined: () => import('@ant-design/icons-vue/es/icons/QuestionOutlined.js'),
  RadarChartOutlined: () => import('@ant-design/icons-vue/es/icons/RadarChartOutlined.js'),
  RadiusBottomleftOutlined: () =>
    import('@ant-design/icons-vue/es/icons/RadiusBottomleftOutlined.js'),
  RadiusBottomrightOutlined: () =>
    import('@ant-design/icons-vue/es/icons/RadiusBottomrightOutlined.js'),
  RadiusSettingOutlined: () => import('@ant-design/icons-vue/es/icons/RadiusSettingOutlined.js'),
  RadiusUpleftOutlined: () => import('@ant-design/icons-vue/es/icons/RadiusUpleftOutlined.js'),
  RadiusUprightOutlined: () => import('@ant-design/icons-vue/es/icons/RadiusUprightOutlined.js'),
  ReadFilled: () => import('@ant-design/icons-vue/es/icons/ReadFilled.js'),
  ReadOutlined: () => import('@ant-design/icons-vue/es/icons/ReadOutlined.js'),
  ReconciliationFilled: () => import('@ant-design/icons-vue/es/icons/ReconciliationFilled.js'),
  ReconciliationTwoTone: () => import('@ant-design/icons-vue/es/icons/ReconciliationTwoTone.js'),
  RedEnvelopeFilled: () => import('@ant-design/icons-vue/es/icons/RedEnvelopeFilled.js'),
  RedEnvelopeOutlined: () => import('@ant-design/icons-vue/es/icons/RedEnvelopeOutlined.js'),
  RedEnvelopeTwoTone: () => import('@ant-design/icons-vue/es/icons/RedEnvelopeTwoTone.js'),
  RedditCircleFilled: () => import('@ant-design/icons-vue/es/icons/RedditCircleFilled.js'),
  RedditOutlined: () => import('@ant-design/icons-vue/es/icons/RedditOutlined.js'),
  RedditSquareFilled: () => import('@ant-design/icons-vue/es/icons/RedditSquareFilled.js'),
  RedoOutlined: () => import('@ant-design/icons-vue/es/icons/RedoOutlined.js'),
  RestFilled: () => import('@ant-design/icons-vue/es/icons/RestFilled.js'),
  RestTwoTone: () => import('@ant-design/icons-vue/es/icons/RestTwoTone.js'),
  RightCircleFilled: () => import('@ant-design/icons-vue/es/icons/RightCircleFilled.js'),
  RightCircleOutlined: () => import('@ant-design/icons-vue/es/icons/RightCircleOutlined.js'),
  RightCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/RightCircleTwoTone.js'),
  RightSquareFilled: () => import('@ant-design/icons-vue/es/icons/RightSquareFilled.js'),
  RightSquareOutlined: () => import('@ant-design/icons-vue/es/icons/RightSquareOutlined.js'),
  RightSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/RightSquareTwoTone.js'),
  RobotFilled: () => import('@ant-design/icons-vue/es/icons/RobotFilled.js'),
  RobotOutlined: () => import('@ant-design/icons-vue/es/icons/RobotOutlined.js'),
  RocketFilled: () => import('@ant-design/icons-vue/es/icons/RocketFilled.js'),
  RocketOutlined: () => import('@ant-design/icons-vue/es/icons/RocketOutlined.js'),
  RocketTwoTone: () => import('@ant-design/icons-vue/es/icons/RocketTwoTone.js'),
  RollbackOutlined: () => import('@ant-design/icons-vue/es/icons/RollbackOutlined.js'),
  SafetyCertificateFilled: () =>
    import('@ant-design/icons-vue/es/icons/SafetyCertificateFilled.js'),
  SafetyCertificateTwoTone: () =>
    import('@ant-design/icons-vue/es/icons/SafetyCertificateTwoTone.js'),
  SafetyOutlined: () => import('@ant-design/icons-vue/es/icons/SafetyOutlined.js'),
  SaveFilled: () => import('@ant-design/icons-vue/es/icons/SaveFilled.js'),
  SaveOutlined: () => import('@ant-design/icons-vue/es/icons/SaveOutlined.js'),
  SaveTwoTone: () => import('@ant-design/icons-vue/es/icons/SaveTwoTone.js'),
  ScanOutlined: () => import('@ant-design/icons-vue/es/icons/ScanOutlined.js'),
  ScheduleFilled: () => import('@ant-design/icons-vue/es/icons/ScheduleFilled.js'),
  ScheduleTwoTone: () => import('@ant-design/icons-vue/es/icons/ScheduleTwoTone.js'),
  ScissorOutlined: () => import('@ant-design/icons-vue/es/icons/ScissorOutlined.js'),
  SecurityScanFilled: () => import('@ant-design/icons-vue/es/icons/SecurityScanFilled.js'),
  SecurityScanOutlined: () => import('@ant-design/icons-vue/es/icons/SecurityScanOutlined.js'),
  SecurityScanTwoTone: () => import('@ant-design/icons-vue/es/icons/SecurityScanTwoTone.js'),
  SelectOutlined: () => import('@ant-design/icons-vue/es/icons/SelectOutlined.js'),
  SettingFilled: () => import('@ant-design/icons-vue/es/icons/SettingFilled.js'),
  SettingTwoTone: () => import('@ant-design/icons-vue/es/icons/SettingTwoTone.js'),
  ShakeOutlined: () => import('@ant-design/icons-vue/es/icons/ShakeOutlined.js'),
  ShareAltOutlined: () => import('@ant-design/icons-vue/es/icons/ShareAltOutlined.js'),
  ShopFilled: () => import('@ant-design/icons-vue/es/icons/ShopFilled.js'),
  ShopTwoTone: () => import('@ant-design/icons-vue/es/icons/ShopTwoTone.js'),
  ShoppingFilled: () => import('@ant-design/icons-vue/es/icons/ShoppingFilled.js'),
  ShoppingTwoTone: () => import('@ant-design/icons-vue/es/icons/ShoppingTwoTone.js'),
  ShrinkOutlined: () => import('@ant-design/icons-vue/es/icons/ShrinkOutlined.js'),
  SignalFilled: () => import('@ant-design/icons-vue/es/icons/SignalFilled.js'),
  SisternodeOutlined: () => import('@ant-design/icons-vue/es/icons/SisternodeOutlined.js'),
  SketchCircleFilled: () => import('@ant-design/icons-vue/es/icons/SketchCircleFilled.js'),
  SketchOutlined: () => import('@ant-design/icons-vue/es/icons/SketchOutlined.js'),
  SketchSquareFilled: () => import('@ant-design/icons-vue/es/icons/SketchSquareFilled.js'),
  SkinFilled: () => import('@ant-design/icons-vue/es/icons/SkinFilled.js'),
  SkinOutlined: () => import('@ant-design/icons-vue/es/icons/SkinOutlined.js'),
  SkinTwoTone: () => import('@ant-design/icons-vue/es/icons/SkinTwoTone.js'),
  SkypeFilled: () => import('@ant-design/icons-vue/es/icons/SkypeFilled.js'),
  SkypeOutlined: () => import('@ant-design/icons-vue/es/icons/SkypeOutlined.js'),
  SlackCircleFilled: () => import('@ant-design/icons-vue/es/icons/SlackCircleFilled.js'),
  SlackOutlined: () => import('@ant-design/icons-vue/es/icons/SlackOutlined.js'),
  SlackSquareFilled: () => import('@ant-design/icons-vue/es/icons/SlackSquareFilled.js'),
  SlackSquareOutlined: () => import('@ant-design/icons-vue/es/icons/SlackSquareOutlined.js'),
  SlidersFilled: () => import('@ant-design/icons-vue/es/icons/SlidersFilled.js'),
  SlidersTwoTone: () => import('@ant-design/icons-vue/es/icons/SlidersTwoTone.js'),
  SmallDashOutlined: () => import('@ant-design/icons-vue/es/icons/SmallDashOutlined.js'),
  SmileFilled: () => import('@ant-design/icons-vue/es/icons/SmileFilled.js'),
  SmileOutlined: () => import('@ant-design/icons-vue/es/icons/SmileOutlined.js'),
  SmileTwoTone: () => import('@ant-design/icons-vue/es/icons/SmileTwoTone.js'),
  SnippetsFilled: () => import('@ant-design/icons-vue/es/icons/SnippetsFilled.js'),
  SnippetsOutlined: () => import('@ant-design/icons-vue/es/icons/SnippetsOutlined.js'),
  SnippetsTwoTone: () => import('@ant-design/icons-vue/es/icons/SnippetsTwoTone.js'),
  SortAscendingOutlined: () => import('@ant-design/icons-vue/es/icons/SortAscendingOutlined.js'),
  SortDescendingOutlined: () => import('@ant-design/icons-vue/es/icons/SortDescendingOutlined.js'),
  SoundFilled: () => import('@ant-design/icons-vue/es/icons/SoundFilled.js'),
  SoundOutlined: () => import('@ant-design/icons-vue/es/icons/SoundOutlined.js'),
  SoundTwoTone: () => import('@ant-design/icons-vue/es/icons/SoundTwoTone.js'),
  SplitCellsOutlined: () => import('@ant-design/icons-vue/es/icons/SplitCellsOutlined.js'),
  StarOutlined: () => import('@ant-design/icons-vue/es/icons/StarOutlined.js'),
  StarTwoTone: () => import('@ant-design/icons-vue/es/icons/StarTwoTone.js'),
  StepBackwardFilled: () => import('@ant-design/icons-vue/es/icons/StepBackwardFilled.js'),
  StepBackwardOutlined: () => import('@ant-design/icons-vue/es/icons/StepBackwardOutlined.js'),
  StepForwardFilled: () => import('@ant-design/icons-vue/es/icons/StepForwardFilled.js'),
  StepForwardOutlined: () => import('@ant-design/icons-vue/es/icons/StepForwardOutlined.js'),
  StopFilled: () => import('@ant-design/icons-vue/es/icons/StopFilled.js'),
  StopOutlined: () => import('@ant-design/icons-vue/es/icons/StopOutlined.js'),
  StopTwoTone: () => import('@ant-design/icons-vue/es/icons/StopTwoTone.js'),
  StrikethroughOutlined: () => import('@ant-design/icons-vue/es/icons/StrikethroughOutlined.js'),
  SubnodeOutlined: () => import('@ant-design/icons-vue/es/icons/SubnodeOutlined.js'),
  SwapLeftOutlined: () => import('@ant-design/icons-vue/es/icons/SwapLeftOutlined.js'),
  SwitcherFilled: () => import('@ant-design/icons-vue/es/icons/SwitcherFilled.js'),
  SwitcherOutlined: () => import('@ant-design/icons-vue/es/icons/SwitcherOutlined.js'),
  SwitcherTwoTone: () => import('@ant-design/icons-vue/es/icons/SwitcherTwoTone.js'),
  SyncOutlined: () => import('@ant-design/icons-vue/es/icons/SyncOutlined.js'),
  TabletFilled: () => import('@ant-design/icons-vue/es/icons/TabletFilled.js'),
  TabletOutlined: () => import('@ant-design/icons-vue/es/icons/TabletOutlined.js'),
  TabletTwoTone: () => import('@ant-design/icons-vue/es/icons/TabletTwoTone.js'),
  TagFilled: () => import('@ant-design/icons-vue/es/icons/TagFilled.js'),
  TagOutlined: () => import('@ant-design/icons-vue/es/icons/TagOutlined.js'),
  TagTwoTone: () => import('@ant-design/icons-vue/es/icons/TagTwoTone.js'),
  TagsFilled: () => import('@ant-design/icons-vue/es/icons/TagsFilled.js'),
  TagsTwoTone: () => import('@ant-design/icons-vue/es/icons/TagsTwoTone.js'),
  TaobaoCircleFilled: () => import('@ant-design/icons-vue/es/icons/TaobaoCircleFilled.js'),
  TaobaoCircleOutlined: () => import('@ant-design/icons-vue/es/icons/TaobaoCircleOutlined.js'),
  TaobaoOutlined: () => import('@ant-design/icons-vue/es/icons/TaobaoOutlined.js'),
  TaobaoSquareFilled: () => import('@ant-design/icons-vue/es/icons/TaobaoSquareFilled.js'),
  ThunderboltFilled: () => import('@ant-design/icons-vue/es/icons/ThunderboltFilled.js'),
  ThunderboltOutlined: () => import('@ant-design/icons-vue/es/icons/ThunderboltOutlined.js'),
  ThunderboltTwoTone: () => import('@ant-design/icons-vue/es/icons/ThunderboltTwoTone.js'),
  ToTopOutlined: () => import('@ant-design/icons-vue/es/icons/ToTopOutlined.js'),
  ToolFilled: () => import('@ant-design/icons-vue/es/icons/ToolFilled.js'),
  ToolTwoTone: () => import('@ant-design/icons-vue/es/icons/ToolTwoTone.js'),
  TrademarkCircleFilled: () => import('@ant-design/icons-vue/es/icons/TrademarkCircleFilled.js'),
  TrademarkCircleOutlined: () =>
    import('@ant-design/icons-vue/es/icons/TrademarkCircleOutlined.js'),
  TrademarkCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/TrademarkCircleTwoTone.js'),
  TrademarkOutlined: () => import('@ant-design/icons-vue/es/icons/TrademarkOutlined.js'),
  TransactionOutlined: () => import('@ant-design/icons-vue/es/icons/TransactionOutlined.js'),
  TranslationOutlined: () => import('@ant-design/icons-vue/es/icons/TranslationOutlined.js'),
  TrophyFilled: () => import('@ant-design/icons-vue/es/icons/TrophyFilled.js'),
  TrophyOutlined: () => import('@ant-design/icons-vue/es/icons/TrophyOutlined.js'),
  TrophyTwoTone: () => import('@ant-design/icons-vue/es/icons/TrophyTwoTone.js'),
  TwitterCircleFilled: () => import('@ant-design/icons-vue/es/icons/TwitterCircleFilled.js'),
  TwitterOutlined: () => import('@ant-design/icons-vue/es/icons/TwitterOutlined.js'),
  TwitterSquareFilled: () => import('@ant-design/icons-vue/es/icons/TwitterSquareFilled.js'),
  UnderlineOutlined: () => import('@ant-design/icons-vue/es/icons/UnderlineOutlined.js'),
  UndoOutlined: () => import('@ant-design/icons-vue/es/icons/UndoOutlined.js'),
  UngroupOutlined: () => import('@ant-design/icons-vue/es/icons/UngroupOutlined.js'),
  UnlockFilled: () => import('@ant-design/icons-vue/es/icons/UnlockFilled.js'),
  UnlockOutlined: () => import('@ant-design/icons-vue/es/icons/UnlockOutlined.js'),
  UnlockTwoTone: () => import('@ant-design/icons-vue/es/icons/UnlockTwoTone.js'),
  UnorderedListOutlined: () => import('@ant-design/icons-vue/es/icons/UnorderedListOutlined.js'),
  UpCircleFilled: () => import('@ant-design/icons-vue/es/icons/UpCircleFilled.js'),
  UpCircleOutlined: () => import('@ant-design/icons-vue/es/icons/UpCircleOutlined.js'),
  UpCircleTwoTone: () => import('@ant-design/icons-vue/es/icons/UpCircleTwoTone.js'),
  UpSquareFilled: () => import('@ant-design/icons-vue/es/icons/UpSquareFilled.js'),
  UpSquareOutlined: () => import('@ant-design/icons-vue/es/icons/UpSquareOutlined.js'),
  UpSquareTwoTone: () => import('@ant-design/icons-vue/es/icons/UpSquareTwoTone.js'),
  UploadOutlined: () => import('@ant-design/icons-vue/es/icons/UploadOutlined.js'),
  UsbFilled: () => import('@ant-design/icons-vue/es/icons/UsbFilled.js'),
  UsbOutlined: () => import('@ant-design/icons-vue/es/icons/UsbOutlined.js'),
  UsbTwoTone: () => import('@ant-design/icons-vue/es/icons/UsbTwoTone.js'),
  UserAddOutlined: () => import('@ant-design/icons-vue/es/icons/UserAddOutlined.js'),
  UserDeleteOutlined: () => import('@ant-design/icons-vue/es/icons/UserDeleteOutlined.js'),
  UserSwitchOutlined: () => import('@ant-design/icons-vue/es/icons/UserSwitchOutlined.js'),
  UsergroupAddOutlined: () => import('@ant-design/icons-vue/es/icons/UsergroupAddOutlined.js'),
  UsergroupDeleteOutlined: () =>
    import('@ant-design/icons-vue/es/icons/UsergroupDeleteOutlined.js'),
  VerifiedOutlined: () => import('@ant-design/icons-vue/es/icons/VerifiedOutlined.js'),
  VerticalAlignBottomOutlined: () =>
    import('@ant-design/icons-vue/es/icons/VerticalAlignBottomOutlined.js'),
  VerticalAlignMiddleOutlined: () =>
    import('@ant-design/icons-vue/es/icons/VerticalAlignMiddleOutlined.js'),
  VerticalLeftOutlined: () => import('@ant-design/icons-vue/es/icons/VerticalLeftOutlined.js'),
  VerticalRightOutlined: () => import('@ant-design/icons-vue/es/icons/VerticalRightOutlined.js'),
  VideoCameraAddOutlined: () => import('@ant-design/icons-vue/es/icons/VideoCameraAddOutlined.js'),
  VideoCameraFilled: () => import('@ant-design/icons-vue/es/icons/VideoCameraFilled.js'),
  VideoCameraOutlined: () => import('@ant-design/icons-vue/es/icons/VideoCameraOutlined.js'),
  VideoCameraTwoTone: () => import('@ant-design/icons-vue/es/icons/VideoCameraTwoTone.js'),
  WalletFilled: () => import('@ant-design/icons-vue/es/icons/WalletFilled.js'),
  WalletTwoTone: () => import('@ant-design/icons-vue/es/icons/WalletTwoTone.js'),
  WarningTwoTone: () => import('@ant-design/icons-vue/es/icons/WarningTwoTone.js'),
  WechatFilled: () => import('@ant-design/icons-vue/es/icons/WechatFilled.js'),
  WechatOutlined: () => import('@ant-design/icons-vue/es/icons/WechatOutlined.js'),
  WeiboCircleFilled: () => import('@ant-design/icons-vue/es/icons/WeiboCircleFilled.js'),
  WeiboCircleOutlined: () => import('@ant-design/icons-vue/es/icons/WeiboCircleOutlined.js'),
  WeiboOutlined: () => import('@ant-design/icons-vue/es/icons/WeiboOutlined.js'),
  WeiboSquareFilled: () => import('@ant-design/icons-vue/es/icons/WeiboSquareFilled.js'),
  WeiboSquareOutlined: () => import('@ant-design/icons-vue/es/icons/WeiboSquareOutlined.js'),
  WhatsAppOutlined: () => import('@ant-design/icons-vue/es/icons/WhatsAppOutlined.js'),
  WifiOutlined: () => import('@ant-design/icons-vue/es/icons/WifiOutlined.js'),
  WindowsFilled: () => import('@ant-design/icons-vue/es/icons/WindowsFilled.js'),
  WindowsOutlined: () => import('@ant-design/icons-vue/es/icons/WindowsOutlined.js'),
  WomanOutlined: () => import('@ant-design/icons-vue/es/icons/WomanOutlined.js'),
  YahooFilled: () => import('@ant-design/icons-vue/es/icons/YahooFilled.js'),
  YahooOutlined: () => import('@ant-design/icons-vue/es/icons/YahooOutlined.js'),
  YoutubeFilled: () => import('@ant-design/icons-vue/es/icons/YoutubeFilled.js'),
  YoutubeOutlined: () => import('@ant-design/icons-vue/es/icons/YoutubeOutlined.js'),
  YuqueFilled: () => import('@ant-design/icons-vue/es/icons/YuqueFilled.js'),
  YuqueOutlined: () => import('@ant-design/icons-vue/es/icons/YuqueOutlined.js'),
  ZhihuCircleFilled: () => import('@ant-design/icons-vue/es/icons/ZhihuCircleFilled.js'),
  ZhihuOutlined: () => import('@ant-design/icons-vue/es/icons/ZhihuOutlined.js'),
  ZhihuSquareFilled: () => import('@ant-design/icons-vue/es/icons/ZhihuSquareFilled.js'),
};

export function isAntIconName(value: string): value is AntIconName {
  return antIconNameSet.has(value);
}
