spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DRIP_DB_URL}
    username: ${DRIP_DB_USERNAME}
    password: ${DRIP_DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${DRIP_REDIS_HOST}
      port: ${DRIP_REDIS_PORT:6379}
      password: ${DRIP_REDIS_PASSWORD:}
