server:
  host: 0.0.0.0
  port: 9001
mysql:
  host: localhost
  port: 3307
  database: drip-manager
  username: root
  password: root
redis:
  host: localhost
  port: 6379
  database: 0
token:
  name: Authorization
  timeoutSeconds: 28800
  activeTimeoutSeconds: 1800
job:
  scriptDir: ../scripts
file:
  uploadDir: uploads
  publicBaseUrl: /uploads
